service:
  name: Serverless
  identifier: Serverless
  serviceDefinition:
    type: ServerlessAwsLambda
    spec:
      manifests:
        - manifest:
            identifier: serverless
            type: ServerlessAwsLambda
            spec:
              store:
                type: Github
                spec:
                  connectorRef: serverlessgitconnector
                  gitFetchType: Branch
                  paths:
                    - serverless-lambda/backend/
                  branch: master
              configOverridePath: ""
  gitOpsEnabled: false
