pipeline:
  name: print secret
  identifier: print_secret
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: print secret
        identifier: print_secret
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: "echo \"text secret is: \" <+secrets.getValue(\"docsecret\")>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
