trigger:
  name: custom-trigger
  identifier: customtrigger
  enabled: true
  description: ""
  tags: {}
  stagesToExecute: []
  orgIdentifier: ORGANIZATION_ID
  projectIdentifier: PROJECT_ID
  pipelineIdentifier: PIPELINE_ID
  source:
    type: Webhook
    spec:
      type: Custom
      spec:
        payloadConditions: []
        headerConditions: []
