pipeline:
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: hello_world
        identifier: helloworld
        description: ""
        type: Deployment
        spec:
          deploymentType: GoogleCloudFunctions
          deploymentMetadata:
            environmentType: GenOne
          execution:
            steps:
              - step:
                  type: DeployCloudFunctionGenOne
                  name: DeployCloudFunctionGenOne_1
                  identifier: DeployCloudFunctionGenOne_1
                  spec:
                    updateFieldMask: ""
                  timeout: 10m
            rollbackSteps:
              - step:
                  type: RollbackCloudFunctionGenOne
                  name: RollbackCloudFunctionGenOne_1
                  identifier: RollbackCloudFunctionGenOne_1
                  spec: {}
                  timeout: 10m
          service:
            serviceRef: hello_world
            serviceInputs:
              serviceDefinition:
                type: GoogleCloudFunctions
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: harnessdevenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: gcpk8s
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables: []
  identifier: hello_world
  name: hello_world
