service:
  name: hello_world
  identifier: hello_world
  tags: {}
  serviceDefinition:
    spec:
      environmentType: GenOne
      manifests:
        - manifest:
            identifier: hello_world
            type: GoogleCloudFunctionGenOneDefinition
            spec:
              store:
                type: Github
                spec:
                  connectorRef: harnessgitconnector
                  gitFetchType: Branch
                  paths:
                    - google_cloud_function/hello_world.yaml
                  branch: master
      artifacts:
        primary:
          primaryArtifactRef: <+input>
          sources:
            - spec:
                connectorRef: gcpconnector
                project: CLOUD_PROJECT_NAME
                bucket: CLOUD_BUCKET_NAME
                artifactPath: hello_world.zip
              identifier: hello_world
              type: GoogleCloudStorage
    type: GoogleCloudFunctions
