service:
  name: hello_http
  identifier: hello_http
  tags: {}
  serviceDefinition:
    spec:
      environmentType: GenTwo
      manifests:
        - manifest:
            identifier: hello_http
            type: GoogleCloudFunctionDefinition
            spec:
              store:
                type: Github
                spec:
                  connectorRef: harnessgitconnector
                  gitFetchType: Branch
                  paths:
                    - google_cloud_function/hello_http.yaml
                  branch: master
      artifacts:
        primary:
          primaryArtifactRef: <+input>
          sources:
            - spec:
                connectorRef: gcpconnector
                project: CLOUD_PROJECT_NAME
                bucket: CLOUD_BUCKET_NAME
                artifactPath: helloHttp.zip
              identifier: hello_http
              type: GoogleCloudStorage
    type: GoogleCloudFunctions
